version: '3.9'

services:

  gitlab:
    image: gitlab/gitlab-ee:16.8.2-ee.0
    container_name: gitlab
    restart: always
    hostname: 'gitlab.example.com'
    environment:
      GITLAB_OMNIBUS_CONFIG: |
        # Add any other gitlab.rb configuration here, each on its own line
        external_url 'https://gitlab.example.com'
    expose:
      - '80:'
      - '443'
      - '8022'
    volumes:
      - './config:/etc/gitlab'
      - './logs:/var/log/gitlab'
      - './data:/var/opt/gitlab'
    shm_size: '256m'
    deploy:
      resources:
        limits:
          cpus: '1.5'
          memory: 3GB
    networks:
      - nginx

  nginx:
    image: nginx:1.23.2-alpine
    container_name: nginx
    volumes:
      - type: bind
        source: ./nginx
        target: /etc/nginx/conf.d
        read_only: true
    depends_on:
      - gitlab
    ports:
      - target: 80
        published: 80
        protocol: tcp
        mode: ingress
    restart: always
    deploy:
      resources:
        limits:
          cpus: '0.20'
          memory: 200M
    networks:
      - nginx

networks:
  nginx:
    driver: bridge