version: '3.9'

services:

  gitlab:
    image: gitlab/gitlab-ee:16.8.2-ee.0
    container_name: gitlab
    restart: always
    hostname: 'gitlab.space-cats.com'
    environment:
      GITLAB_OMNIBUS_CONFIG: |
        # Add any other gitlab.rb configuration here, each on its own line
        external_url 'https://gitlab.space-cats.com'
        gitlab_rails['gitlab_shell_ssh_port'] = 2224
    ports:
      - '127.0.0.1:8080:80'
      - '127.0.0.1:8443:443'
      - '2224:22'
    volumes:
      - './config:/etc/gitlab'
      - './logs:/var/log/gitlab'
      - './data:/var/opt/gitlab'
    shm_size: '256m'
    deploy:
      resources:
        limits:
          cpus: '2'
          memory: 3GB
